import { FileText, Download, Calendar, FileBarChart, FileSpreadsheet, FileCheck } from 'lucide-react'

const REPORTS = [
  { id: 1, title: 'Quarterly Academic Report — Q3 SY 2025–2026',  type: 'PDF',   size: '2.4 MB', date: '2026-04-15', icon: FileText, tone: 'red' },
  { id: 2, title: 'Predictive Risk Summary — April 2026',          type: 'PDF',   size: '1.8 MB', date: '2026-04-22', icon: FileBarChart, tone: 'purple' },
  { id: 3, title: 'Attendance Master List — March 2026',           type: 'XLSX',  size: '3.1 MB', date: '2026-04-02', icon: FileSpreadsheet, tone: 'green' },
  { id: 4, title: 'Teacher Performance Evaluation — Q3',           type: 'PDF',   size: '1.2 MB', date: '2026-04-10', icon: FileCheck, tone: 'brand' },
  { id: 5, title: 'Enrollment Forecast Analysis — SY 2026–2027',   type: 'PDF',   size: '950 KB', date: '2026-04-05', icon: FileBarChart, tone: 'purple' },
  { id: 6, title: 'Honor Roll List — Q3',                          type: 'PDF',   size: '420 KB', date: '2026-04-18', icon: FileText, tone: 'amber' },
  { id: 7, title: 'Intervention Outcomes Report — Q2 vs Q3',       type: 'PDF',   size: '1.5 MB', date: '2026-04-20', icon: FileBarChart, tone: 'purple' },
  { id: 8, title: 'Section-level Grade Distribution',              type: 'XLSX',  size: '2.7 MB', date: '2026-03-28', icon: FileSpreadsheet, tone: 'green' }
]

const tones = {
  red:    'bg-red-50 text-red-700',
  green:  'bg-emerald-50 text-emerald-700',
  brand:  'bg-brand-50 text-brand-700',
  amber:  'bg-amber-50 text-amber-700',
  purple: 'bg-purple-50 text-purple-700'
}

export default function Reports() {
  return (
    <div className="p-8 space-y-6">
      <div className="card p-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-base font-bold text-slate-900">Generated Reports</h3>
            <p className="text-xs text-slate-500">Auto-generated by the analytics engine and admin staff</p>
          </div>
          <button className="btn-primary"><FileText className="w-4 h-4" /> New Report</button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {REPORTS.map((r) => {
            const Icon = r.icon
            return (
              <div key={r.id} className="flex items-start gap-4 p-4 rounded-xl border border-slate-200 hover:shadow-md transition-shadow bg-white">
                <div className={`w-12 h-12 rounded-lg flex items-center justify-center flex-shrink-0 ${tones[r.tone]}`}>
                  <Icon className="w-6 h-6" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-bold text-slate-900">{r.title}</p>
                  <div className="mt-2 flex items-center gap-3 text-xs text-slate-500">
                    <span className="badge-slate">{r.type}</span>
                    <span>{r.size}</span>
                    <span className="inline-flex items-center gap-1"><Calendar className="w-3 h-3" /> {r.date}</span>
                  </div>
                </div>
                <button className="p-2 rounded-lg hover:bg-slate-100 text-slate-600">
                  <Download className="w-4 h-4" />
                </button>
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
